package com.example.ui.localization

import com.example.ui.viewmodel.AppLanguage

object Localization {
    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.EN -> englishDict[key] ?: key
            AppLanguage.FA -> persianDict[key] ?: key
        }
    }

    private val englishDict = mapOf(
        "app_name" to "Nova Radar",
        "tab_radar" to "Radar",
        "tab_results" to "Results",
        "tab_installer" to "Easy Installer",
        "tab_settings" to "Settings",
        "tab_logs" to "Logs",
        "tab_about" to "About Us",
        "coming_soon" to "Coming Soon",
        "scanner_title" to "SCANNER",
        "results_title" to "RESULTS",
        "start_scan" to "Start Scan",
        "stop_scan" to "STOP ENGINE",
        "scanned" to "Scanned",
        "alive" to "Alive",
        "dead" to "Dead",
        "eta" to "ETA",
        "ready_to_scan" to "Ready to scan",
        "current_scanning" to "SCANNING SUBNET...",
        "port_configuration" to "PORT CONFIGURATION",
        "ip_sources" to "IP SOURCES",
        "enabled" to "Enabled",
        "disabled" to "Disabled",
        "theme" to "THEME STYLE",
        "language" to "UI LANGUAGE",
        "gemini_dark" to "Gemini Dark (Multi-color)",
        "gemini_light" to "Gemini Light (Multi-color)",
        "solarized_dark" to "Solarized Dark",
        "standard_dark" to "Standard Dark",
        "sec_ports" to "Active Ports",
        "sec_sources" to "Active Subnets",
        "about_title" to "Nova Radar",
        "about_sub" to "ساخته شده توسط گروه نوا پروکسی",
        "about_version" to "Nova Radar v1.0.0",
        "telegram_channel" to "Telegram Channel",
        "github_repo" to "GitHub Repository",
        "author_contact" to "Author Contact",
        "copy_top10" to "Copy Top 10 IPs",
        "copied_note" to "Top 10 lowest ping IPs copied to clipboard!",
        "reset" to "Reset",
        "all" to "All",
        "clear" to "Clear",
        "network_diagnostic" to "NETWORK DIAGNOSTIC",
        "no_results" to "No results yet",
        "no_results_desc" to "Select ports and click Start Scan",
        "alive_results" to "ALIVE RESULTS",
        "clear_logs" to "Clear Logs",
        "alert_settings" to "VIBRATION & ALERT CONFIG",
        "vibrate_finish" to "Vibrate on Complete",
        "vibrate_error" to "Vibrate on Warnings",
        "notify_error" to "Notifications on Alerts",
        "export_results" to "Export Clean IPs (.txt)",
        "permission_dialog_title" to "Permissions Required",
        "permission_dialog_desc" to "This app needs Notification and Storage permissions to function correctly.",
        "grant_permissions" to "Grant Permissions",
        "select_all" to "Select All",
        "clear_all" to "Clear All"
    )

    private val persianDict = mapOf(
        "app_name" to "نوا رادار",
        "tab_radar" to "رادار",
        "tab_results" to "نتایج",
        "tab_installer" to "ایزی انستالر",
        "tab_settings" to "تنظیمات",
        "tab_logs" to "لاگ",
        "tab_about" to "درباره ما",
        "coming_soon" to "بزودی",
        "scanner_title" to "اسکنر",
        "results_title" to "نتایج",
        "start_scan" to "شروع اسکن",
        "stop_scan" to "توقف موتور",
        "scanned" to "اسکن شده",
        "alive" to "فعال",
        "dead" to "خاموش",
        "eta" to "زمان باقی‌مانده",
        "ready_to_scan" to "آماده برای اسکن",
        "current_scanning" to "در حال اسکن رنج...",
        "port_configuration" to "تنظیمات پورت",
        "ip_sources" to "رنج‌های آی‌پی هدف",
        "enabled" to "فعال",
        "disabled" to "غیر فعال",
        "theme" to "تم نمایشی برنامه",
        "language" to "زبان برنامه",
        "gemini_dark" to "جمنای دارک (گرادینت)",
        "gemini_light" to "جمنای لایت (گرادینت)",
        "solarized_dark" to "سولارایزد تاریک",
        "standard_dark" to "مشکی استاندارد",
        "sec_ports" to "پورت‌های فعال",
        "sec_sources" to "رنج‌های آی‌پی فعال",
        "about_title" to "Nova Radar",
        "about_sub" to "ساخته شده توسط گروه نوا پروکسی",
        "about_version" to "نسخه نوا رادار v1.0.0",
        "telegram_channel" to "کانال تلگرام نوا پروکسی",
        "github_repo" to "صفحه گیت‌هاب پروژه",
        "author_contact" to "آیدی سازنده",
        "copy_top10" to "کپی کردن لیست ۱۰ آی‌پی برتر",
        "copied_note" to "لیست ۱۰ رنج آی‌پی برتر در کلیپ‌بورد کپی شد!",
        "reset" to "بازنشانی",
        "all" to "همه",
        "clear" to "پاک کردن",
        "network_diagnostic" to "عیب‌یابی پیشرفته شبکه",
        "no_results" to "هنوز نتیجه‌ای یافت نشده",
        "no_results_desc" to "پورت‌ها را انتخاب کرده و دکمه شروع اسکن را بزنید",
        "alive_results" to "لیست آی‌پی‌های فعال",
        "clear_logs" to "پاک کردن لاگ‌ها",
        "alert_settings" to "تنظیمات لرزش و اعلام هشدارهای برنامه",
        "vibrate_finish" to "لرزش پس از اتمام فرآیند اسکن",
        "vibrate_error" to "لرزش در هنگام بروز اخطار",
        "notify_error" to "نمایش نوتیفیکیشن در زمان هشدار",
        "export_results" to "خروجی گرفتن از آی‌پی‌ها به فایل (.txt)",
        "permission_dialog_title" to "دسترسی‌های مورد نیاز برنامه",
        "permission_dialog_desc" to "این برنامه برای عملکرد صحیح خود، به دسترسی‌های نوتیفیکیشن و ذخیره‌سازی نیاز دارد.",
        "grant_permissions" to "اعطای دسترسی‌های لازم",
        "select_all" to "انتخاب همه",
        "clear_all" to "پاکسازی همه"
    )
}
